name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build, restore, test
      shell: pwsh
      run: ./pipelines/build-dotnet.ps1

  armv64_job:
      name: Build and Test for arm64
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && \
              apt-get install sudo && \
              apt install wget -y && \
              wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
              sudo dpkg -i packages-microsoft-prod.deb && \
              rm packages-microsoft-prod.deb && \
              sudo apt update && \
              sudo apt install -y apt-transport-https && \
              sudo apt install dotnet-sdk-6.0 && \
              sudo apt-get install aspnetcore-runtime-6.0 && \
              sudo apt-get install dotnet-runtime-6.0 && \
              dotnet --version && \
              cd dotnet && \
              dotnet restore && \
              dotnet build -c Release && \
              dotnet test -c Release && \
              deactivate'
