name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build, restore, test
      shell: pwsh
      run: ./pipelines/build-dotnet.ps1

  armv64_job:
      name: Build and Test for arm64
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && \
              apt-get install sudo && \
              apt install wget -y && \
              wget https://github.com/dotnet/sdk/archive/refs/tags/v7.0.203.tar.gz && \
              DOTNET_FILE=v7.0.203.tar.gz && \
              export DOTNET_ROOT=$(pwd)/.dotnet && \
              mkdir -p "$DOTNET_ROOT" && tar zxf "$DOTNET_FILE" -C "$DOTNET_ROOT" && \
              export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools && \
              dotnet --version && \
              cd dotnet && \
              dotnet restore && \
              dotnet build -c Release && \
              dotnet test -c Release && \
              deactivate'
