name: spa build

on:
  push:
    branches: 
      - '*'
    paths: [ 'web/serverless-microservices-web/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web/serverless-microservices-web

    strategy:
      matrix:
        # https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=csharp%2Cv4#languages
        node-version: [14.x, 12.x, 10.x]

    steps:
    - uses: actions/checkout@v2 
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./web/serverless-microservices-web
    - run: npm install
    - run: npm run build
